package Ankama_Fight.ui.timeline
{
   import Ankama_Fight.Api;
   import com.ankamagames.berilia.components.EntityDisplayer;
   import com.ankamagames.berilia.components.Label;
   import com.ankamagames.berilia.components.ProgressBar;
   import com.ankamagames.berilia.components.Texture;
   import com.ankamagames.berilia.enums.StatesEnum;
   import com.ankamagames.berilia.types.graphic.ButtonContainer;
   import flash.display.Sprite;
   import flash.filters.BitmapFilterQuality;
   import flash.filters.GlowFilter;
   import flash.geom.ColorTransform;
   import flash.utils.getTimer;
   
   public class Fighter#497
   {
      
      private static const SUMMONED_SCALE:Number = 0.8;
      
      private static const MINIMUM_LIFEBAR_WIDTH:uint = 2;
      
      private static var _framePool:Array;
      
      private static var _freeFrameId:uint = 0;
      
      
      private var _id:Number;
      
      private var _alive:Boolean = true;
      
      private var _isCurrentPlayer:Boolean = false;
      
      private var _summoned:Boolean;
      
      private var _hiddenInPrefight:Boolean;
      
      private var _lifePoints:int;
      
      private var _lifePointsThreshold:int;
      
      private var _shieldPoints:int;
      
      private var _risen:Boolean = false;
      
      private var _highlighted:Boolean = false;
      
      private var _clockStart:int;
      
      private var _turnDuration:int;
      
      private var _turnElapsedTime:uint;
      
      private var _timelineUi:Object;
      
      private var _selected:Boolean = false;
      
      private var _frame:ButtonContainer;
      
      private var _txSelected:Texture;
      
      private var _teamBackground:Texture;
      
      private var _teamDarkBackground:Texture;
      
      private var _teamTimeBackground:Texture;
      
      private var _txUnsorted:Texture;
      
      private var _timeMask:Sprite;
      
      private var _gfx:EntityDisplayer;
      
      private var _gfxMask:Sprite;
      
      private var _pdvGauge:ProgressBar;
      
      private var _pdvThresholdGauge:ProgressBar;
      
      private var _shieldGauge:ProgressBar;
      
      private var _lbl_number:Label;
      
      private var _lbl_waveNumber:Label;
      
      private var _minPdvGauge:uint;
      
      public function Fighter#497(id:Number, timelineUi:Object, num:uint)
      {
      }
      
      private static function nextFrameName() : String
      {
         return ""; //autogenerated
      }
      
      public static function cleanFramesPool() : void
      {
      }
      
      public function get id() : Number
      {
         return null; //autogenerated
      }
      
      public function get alive() : Boolean
      {
         return null; //autogenerated
      }
      
      public function set alive(value:Boolean) : void
      {
      }
      
      public function get summoned() : Boolean
      {
         return null; //autogenerated
      }
      
      public function get hiddenInPrefight() : Boolean
      {
         return null; //autogenerated
      }
      
      public function set hiddenInPrefight(value:Boolean) : void
      {
      }
      
      public function get frame() : ButtonContainer
      {
         return null; //autogenerated
      }
      
      public function get look() : Object
      {
         return null; //autogenerated
      }
      
      public function set look(object:Object) : void
      {
      }
      
      public function get selected() : Boolean
      {
         return null; //autogenerated
      }
      
      public function set selected(value:Boolean) : void
      {
      }
      
      public function get clockStart() : int
      {
         return 0; //autogenerated
      }
      
      public function get turnDuration() : int
      {
         return 0; //autogenerated
      }
      
      public function destroy(force:Boolean = false) : void
      {
      }
      
      public function refreshPdv() : void
      {
      }
      
      public function setPdv(lifePoints:int) : void
      {
      }
      
      public function refreshPdvThreshold(threshold:uint) : void
      {
      }
      
      public function setPdvThreshold(lifePointsThreshold:int) : void
      {
      }
      
      public function refreshShield() : void
      {
      }
      
      public function setShield(currentShield:int) : void
      {
      }
      
      public function startCountDown(turnDuration:int, remainingTime:uint) : void
      {
      }
      
      public function stopCountDown() : void
      {
      }
      
      public function pauseCountDown() : void
      {
      }
      
      public function updateTime(value:Number = 0) : void
      {
      }
      
      public function updateSprite() : void
      {
      }
      
      public function setRisen(value:Boolean, vertical:Boolean, direction:int) : void
      {
      }
      
      public function get risen() : Boolean
      {
         return null; //autogenerated
      }
      
      public function set highlight(value:Boolean) : void
      {
      }
      
      public function updateNumber(num:uint) : void
      {
      }
      
      public function updateUnsortedIcon() : void
      {
      }
      
      public function get isCurrentPlayer() : Boolean
      {
         return null; //autogenerated
      }
      
      private function displayFighter(id:Number, num:uint) : void
      {
      }
      
      private function createFrame(summoned:Boolean) : ButtonContainer
      {
         return null; //autogenerated
      }
      
      private function setAlive(alive:Boolean) : void
      {
      }
      
      private function onEnterFrame() : void
      {
      }
   }
}
