package com.ankamagames.dofus.datacenter.items
{
   import com.ankamagames.dofus.datacenter.effects.EffectInstance;
   import com.ankamagames.dofus.types.IdAccessors;
   import com.ankamagames.jerakine.data.GameData;
   import com.ankamagames.jerakine.data.I18n;
   import com.ankamagames.jerakine.interfaces.IDataCenter;
   
   public class ItemSet#140 implements IDataCenter
   {
      
      public static const MODULE:String = "ItemSets";
      
      public static var idAccessors:IdAccessors;
      
      
      public var id:uint;
      
      public var items:Vector.<uint>;
      
      public var nameId:uint;
      
      public var effects:Vector.<Vector.<EffectInstance>>;
      
      public var bonusIsSecret:Boolean;
      
      private var _name:String;
      
      public function ItemSet#140()
      {
      }
      
      public static function getItemSetById(id:uint) : ItemSet#140
      {
         return null; //autogenerated
      }
      
      public static function getItemSets() : Array
      {
         return null; //autogenerated
      }
      
      public function get name() : String
      {
         return ""; //autogenerated
      }
   }
}
