package Ankama_Party.ui.items
{
   import Ankama_Party.Party;
   import com.ankamagames.berilia.api.UiApi;
   import com.ankamagames.berilia.components.EntityDisplayer;
   import com.ankamagames.berilia.components.ProgressBar;
   import com.ankamagames.berilia.components.Texture;
   import com.ankamagames.berilia.types.graphic.GraphicContainer;
   import com.ankamagames.dofus.internalDatacenter.people.PartyCompanionWrapper;
   import com.ankamagames.dofus.network.ProtocolConstantsEnum;
   import com.ankamagames.dofus.network.enums.PlayerStatusEnum;
   import com.ankamagames.dofus.network.enums.PvpArenaStepEnum;
   import com.ankamagames.dofus.uiApi.MountApi;
   import com.ankamagames.dofus.uiApi.PlayedCharacterApi;
   import com.ankamagames.dofus.uiApi.SystemApi;
   import d2enums.ComponentHookList;
   import d2hooks.ArenaFighterStatusUpdate;
   import d2hooks.ArenaRegistrationStatusUpdate;
   import d2hooks.GameFightEnd;
   import d2hooks.PartyCompanionMemberUpdate;
   import d2hooks.PartyMemberFollowUpdate;
   import d2hooks.PartyMemberLifeThresholdUpdate;
   import d2hooks.PartyMemberLifeUpdate;
   import d2hooks.PartyMemberUpdate;
   import d2hooks.PlayerStatusUpdate;
   import flash.display.Sprite;
   import flash.filters.BitmapFilterQuality;
   import flash.filters.GlowFilter;
   
   public class PartyMember#1818
   {
      
      
      [Api(name="SystemApi")]
      public var sysApi:SystemApi;
      
      [Api(name="UiApi")]
      public var uiApi:UiApi;
      
      [Api(name="MountApi")]
      public var mountApi:MountApi;
      
      [Api(name="PlayedCharacterApi")]
      public var playerApi:PlayedCharacterApi;
      
      private var _data;
      
      private var _selected:Boolean;
      
      private var _playerStatus:String = "";
      
      public var ctr_main:GraphicContainer;
      
      public var tx_bg:Texture;
      
      public var ed_player:EntityDisplayer;
      
      public var tx_leaderCrown:Texture;
      
      public var tx_followArrow:Texture;
      
      public var tx_guest:Texture;
      
      public var tx_arenaStatus:Texture;
      
      public var pb_lifePoints:ProgressBar;
      
      public var pb_lifePointsThreshold:ProgressBar;
      
      public function PartyMember#1818()
      {
      }
      
      public function main(oParam:Object = null) : void
      {
      }
      
      public function get data() : *
      {
         return null; //autogenerated
      }
      
      public function get selected() : Boolean
      {
         return null; //autogenerated
      }
      
      public function update(pData:*, selected:Boolean) : void
      {
      }
      
      public function select(b:Boolean) : void
      {
      }
      
      public function onRollOver(target:Object) : void
      {
      }
      
      public function onArenaFighterStatusUpdate(playerId:Number, answer:Boolean) : void
      {
      }
      
      public function onArenaRegistrationStatusUpdate(isRegistered:Boolean, currentStatus:int) : void
      {
      }
      
      public function onRollOut(target:Object) : void
      {
      }
      
      private function onGameFightEnd(... rest) : void
      {
      }
      
      private function onPartyMemberUpdate(id:int, pId:Number, guest:Boolean) : void
      {
      }
      
      private function onPartyMemberLifeUpdate(id:int, pId:Number, pLifePoints:int, pInitiative:int) : void
      {
      }
      
      private function onPartyMemberLifeThresholdUpdate(id:int, pId:Number, pLifePointsThreshold:int) : void
      {
      }
      
      private function onPartyCompanionMemberUpdate(partyId:int, playerId:Number, index:int, companion:Object) : void
      {
      }
      
      private function onPartyMemberFollowUpdate(partyId:int, memberId:Number, followed:Boolean) : void
      {
      }
      
      private function onPartyMemberStatusUpdate(accountId:uint, playerId:Number, status:uint, message:String) : void
      {
      }
   }
}
