package com.ankama.haapi.client.model
{
   public class ShopArticle#532
   {
      
      
      public var id:Number = 0;
      
      public var key:String = null;
      
      public var name:String = null;
      
      public var subtitle:String = null;
      
      public var description:String = null;
      
      public var currency:String = null;
      
      public var original_price:Number = 0.0;
      
      public var price:Number = 0.0;
      
      public var startdate:Date = null;
      
      public var enddate:Date = null;
      
      public var showCountDown:Boolean = false;
      
      public var stock:Number = 0;
      
      private var _image_obj_class:Array = null;
      
      public var image:Array;
      
      private var _references_obj_class:Array = null;
      
      public var references:Array;
      
      private var _promo_obj_class:Array = null;
      
      public var promo:Array;
      
      private var _media_obj_class:Array = null;
      
      public var media:Array;
      
      private var _metas_obj_class:Array = null;
      
      public var metas:Array;
      
      private var _pricelist_obj_class:Array = null;
      
      public var pricelist:Array;
      
      public var most_precise_category_id:Number = 0;
      
      public function ShopArticle#532()
      {
      }
      
      public function toString() : String
      {
         return ""; //autogenerated
      }
   }
}
