package com.ankamagames.dofus.modules.utils.pathfinding.world
{
   public class Edge#156
   {
      
      
      private var _from:Vertex;
      
      private var _to:Vertex;
      
      private var _transitions:Vector.<Transition>;
      
      public function Edge#156(from:Vertex, to:Vertex)
      {
      }
      
      public function get from() : Vertex
      {
         return null; //autogenerated
      }
      
      public function get to() : Vertex
      {
         return null; //autogenerated
      }
      
      public function get transitions() : Vector.<Transition>
      {
         return null; //autogenerated
      }
      
      public function addTransition(dir:int, type:int, skill:int, criterion:String, transitionMapId:Number, cell:int, id:uint) : void
      {
      }
      
      public function toString() : String
      {
         return ""; //autogenerated
      }
   }
}
